apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config
  namespace: demo
data:
  NEW_FEATURE: "true"

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: demo
spec:
  selector:
    source: demo
    app: spinnaker-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: demo
  labels:
    source: demo
    stack: frontend
    app: spinnaker
spec:
  replicas: 3
  selector:
    matchLabels:
      source: demo
      app: spinnaker
  template:
    metadata:
      labels:
        source: demo
        app: spinnaker
    spec:
      containers:
      - name: primary
        image: 201599078153.dkr.ecr.us-east-1.amazonaws.com/mason-test-ecr
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-demo-config
