apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: spinnaker-staging
  namespace: spinkubstaging
  labels:
    applicationName: spinnaker-staging
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service spinnaker-staging"]'
spec:
  replicas: 3
  selector:
    matchLabels:
      applicationName: spinnaker-staging
  template:
    metadata:
      labels:
        applicationName: spinnaker-staging
    spec:
      containers:
        - name: spinkub-demo-container
          image: 474168465621.dkr.ecr.us-west-2.amazonaws.com/encore
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          env:
          - name: NEW_FEATURE
            value: 'true'

# Trigger !!!

