apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config
  namespace: demo
data:
  NEW_FEATURE: "true"

---

apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: spinnaker-demo
  namespace: demo
  labels:
    applicationName: spinnaker-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      applicationName: spinnaker-demo
  template:
    metadata:
      labels:
        applicationName: spinnaker-demo
    spec:
      containers:
        - name: primary
          image: 201599078153.dkr.ecr.us-east-1.amazonaws.com/mason-test-ecr
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          envFrom:
          - configMapRef:
              name: spinnaker-demo-config

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: demo
spec:
  selector:
    source: demo
    app: spinnaker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer




# Another one
# Another one
# Another one
# Another one
# Secret
